### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by zippy1981**
Needed to explicitly declare encoding on windows python 3.4.2.

### CODE REVIEW

**Comment by fhirschmann** [comment]
Hi Justin,

Thanks for the fix! Would you mind adding

```python
from io import open
```

to `setup.py` for python2 compatibility to this pull request?

**Comment by zippy1981** [comment]
Apparently this isn't enough for the module to work with python 3.4.2 yet, I'll need to work on the module itself. its complaining about xrange().

Expect more pull requests.

**Comment by fhirschmann** [comment]
Thanks Justin.

xrange has become range in Python 3. One simple solution I could think of is something like
```python
import sys
if sys.version_info.major >= 3:
    xrange = range
```

**Comment by zippy1981** [comment]
See my other pull request.

**Pull request closed without merging**
